### ISSUE TITLE
Normalize Extension Samples

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-extension-samples#104]
Together with https://github.com/Microsoft/vscode-docs/issues/1949, we should make samples share the same README structure, code format, etc. This will make the samples consistent easy to consume.

The work is happening in [`ext-docs`](https://github.com/Microsoft/vscode-extension-samples/tree/ext-docs) branch. When I'm done setting the guideline & standard format, I'll create a new item for adapting to the new standard.

### Done

- [x] Add a contributing guideline for extension samples
- [x] Enforce tab-spacing for all JSON files
- [x] :runner: Create a table of all samples with links to guide, etc

### Todo

- [x] Enforce tab-spacing for all TS files
- [x] Remove non-relevant License/Thirdparty in each workspace (This is captured in the root License)
- [x] Make sure `editor.insertSpace`, formatter / linter config are present in each sample
- [x] Create a plan item to track conformity to standard for each extension
- [x] Send PR to fix inconsistencies in yo code generator

**Comment by octref** [comment]
@Tyriar Personally I find it distracting in each sample file. I'd rather have one License file at the root. See good examples such as https://github.com/hokein/electron-sample-apps and https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples

**Comment by Tyriar** [comment]
@octref it's more a legal question than whether you find it distracting though, perhaps it doesn't matter for samples, I'm not sure? @chrisdias?

Also those Google samples seem just as inconsistent as us regarding license in samples.

**Comment by chrisdias** [comment]
If it is all in one repo, having a single top level `LICENSE.md` and `ThirdPartyNotices.txt` at the root is fine.

**Comment by octref** [comment]
PR: https://github.com/Microsoft/vscode-generator-code/pull/149

**Comment by octref** [comment]
Shipped.
